### ISSUE TITLE
画像ファイルの解像度について

### ISSUE THREAD

**Issue by arcage** [crystal-jp/techbookfest2#10]
原稿の中で使用する画像の解像度はどれくらいを目安にすれば良いでしょうか？

**Comment by rosylilly** [comment]
なるべく大きければ大きいほどよいです。

あまりに巨大なら S3 かなんかに置く方式にしますかね。

**Comment by arcage** [comment]
ありがとうございます。

スクリーンショットの切り抜き画像なのでそこまで大きくならないと思いますが，
撮ったままリサイズせずに置いておくことにします。
